export const USER_ACTIONS = { 
  FETCH_RESULTS: "FETCH_RESULTS", 
  SET_RESULTS: "SET_RESULTS", 
  FETCH_EVENTS: "FETCH_EVENTS",
  SET_EVENTS: 'SET_EVENTS', 
  FETCH_SCHEDULING_DATA: "FETCH_SCHEDULING_DATA",
  SET_SCHEDULING_DATA: 'SET_SCHEDULING_DATA',
  FETCH_SELECTED_TRAP: "FETCH_SELECTED_TRAP",
  SET_SELECTED_TRAP:'SET_SELECTED_TRAP',
  FETCH_SHOOTERS: "FETCH_SHOOTERS",
  SET_SHOOTERS: 'SET_SHOOTERS',
  FETCH_SQUADDING_DATA: "FETCH_SQUADDING_DATA",
  SET_SQUADDING_DATA: 'SET_SQUADDING_DATA',
  FETCH_TRAPS: "FETCH_TRAPS",
  SET_TRAPS: 'SET_TRAPS',
  GO_TO_REGISTRATION_PAGE: "GO_TO_REGISTRATION_PAGE",
  LOGOUT: "LOGOUT",


};
